### ISSUE TITLE
web3connect

### ISSUE THREAD

**Issue by ajunge** [clbrge/svelte-web3#1]
Can I use this with web3connect https://github.com/web3connect/web3connect ?

I don't know how to add the provider web3connect returns

**Comment by clbrge** [comment]
It is not yet really supported but I just uploaded a new version which may work at least to get and instantiate a web3 instance :  https://github.com/clbrge/svelte-web3/releases/tag/0.1.3

Could you please try:
```
import { ethereum, web3, isListening, whenReady } from 'svelte-ethereum';
import Web3Connect from "web3connect";

const providerOptions = {
  /* See Provider Options Section */
};

const web3Connect = new Web3Connect.Core({
  network: "mainnet", // optional
  cacheProvider: true, // optional
  providerOptions // required
});

const provider = await web3Connect.connect();
ethereum.setProvider(provider)
```

$web3 should now be instantiated...

I will add better support in a future version.

**Comment by ajunge** [comment]
I got this:

```
/home/ajunge/work/notabene/mvp/node_modules/svelte-web3/dist/index.js:13670
      _btoa = btoa;

ReferenceError: btoa is not defined
    at /home/ajunge/work/notabene/mvp/node_modules/svelte-web3/dist/index.js:13670:7
    at _from (/home/ajunge/work/notabene/mvp/node_modules/svelte-web3/dist/index.js:2:66)
    at Object.<anonymous> (/home/ajunge/work/notabene/mvp/node_modules/svelte-web3/dist/index.js:5:2)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
```

**Comment by clbrge** [comment]
Ok. Thanks for the feedback. I will try to have a look later this week.

**Comment by clbrge** [comment]
@ajunge sorry it too long but could you try again with the new version 1.3.4
Thanks

**Comment by ajunge** [comment]
Oh. I don't have code to test this again. Should we close the issue anyways?

**Comment by clbrge** [comment]
We can leave it open. We try it again myself... Thanks

**Comment by 11reed** [comment]
Is this still not supported?

**Comment by clbrge** [comment]
It is supported since version 2.0.0.
Note: the library has been renamed web3modal, I just released a new version that add an example how to use it... Let me know if you have problem using it @11reed
