### ISSUE TITLE
Polling for transactions taking on the chain

### ISSUE THREAD

**Issue by raghav-kukreti** [clbrge/svelte-web3#11]
Hi,
Thank you for the great work on the repo,
a bit new to working with smart contracts in Svelte, apologies for the noob-ish question;
How does one dynamically update the UI (for ex: adding pending and complete transactions as a Svelte component)
Or more formally how does one watch the chain for transfers and transactions?

**Comment by Garito** [comment]
You should either poll an explorer or use a web3 filter

**Comment by clbrge** [comment]
More examples have been added to the repo and documentation have been updated since this issue was opened. So i will close this for now. @raghav-kukreti don't hesitate to open a new issue but maybe on a more specific/narrow question if needed.
