### ISSUE TITLE
Sveltekit web3 is not defined

### ISSUE THREAD

**Issue by ricardo-rp** [clbrge/svelte-web3#17]
I created an app with sveltekit and globaly disabled SSR. I followed the When I try to access the $web3 store, it crashes saying it is not defined. I could not find what I'm doing wrong in the Readme guide

Here is my code:

```
<script context="module" lang="ts">
	export const prerender = true;
</script>

<script lang="ts">
	import Board from '$lib/components/board/Board.svelte';
	import { onMount } from 'svelte';
	import {
		defaultChainStore,
		web3,
		selectedAccount,
		connected,
	} from 'svelte-web3';

	// Connect to metamask
	onMount(() => defaultChainStore.setBrowserProvider());

	let balance = $web3.eth.getBalance('0x76fc18e74dd215467a5ed990ceb322c94df01de9')

</script>

<svelte:head>
	<title>Tic-tac-toe</title>
</svelte:head>

<section>
	<h1>Tic-tac-toe</h1>

	<Board />
</section>
```

**Comment by clbrge** [comment]
initialization of your component happens before the `onMount`, so at this time, $web3 is indeed not defined.
you could move the "let balance" line inside the `onMount` (and await the `setBrowserProvider`).
Or you use a reactive variable:

```
let balance
$:  if ($web3) { balance = $web3.eth.getBalance('0x76fc18e74dd215467a5ed990ceb322c94df01de9') }
```

**Comment by ricardo-rp** [comment]
@clbrge Thank you very much for your reply.
Sadly, web3 is still not defined. I tried both:
```
        let balance;
	onMount(async () => {
		await defaultChainStore.setBrowserProvider();
		balance = $web3.eth.getBalance('0x76fc18e74dd215467a5ed990ceb322c94df01de9');
	});	
```

and

```
	onMount(() => defaultChainStore.setBrowserProvider());

	let balance;
	$: if ($web3) {
		balance = $web3.eth.getBalance('0x76fc18e74dd215467a5ed990ceb322c94df01de9');
	}
```
This is the repo where the issue is happening. Maybe I did something wrong during the setup?
https://github.com/ricardo-rp/eth-tic-tac-toe
