### ISSUE TITLE
Example of svelte-web3 integration

### ISSUE THREAD

**Issue by miohtama** [clbrge/svelte-web3#21]
Hi,

I recently participated in EthLisbon and used `svelte-web3` for building the frontend. Other users might find this example useful:

https://github.com/tradingstrategy-ai/frontend/blob/master/src/lib/web3/Investor.svelte

The page is live here:

https://tradingstrategy.ai/strategy/ethlisbon

I can add this also to README or another relevant place for those who want to get up to the speed quick with a ready example.

**Comment by clbrge** [comment]
Great news @miohtama ! I can add that to the README but please do a PR if you want! Let me know what you prefer...

**Comment by clbrge** [comment]
Added in release 2.3.3.

**Comment by miohtama** [comment]
Thank you so much @clbrge - I just noticed comment on this issue, for some reason it slipped under my radar.

**Comment by miohtama** [comment]
We also published a post-mortem on developing our site on Svelte / SvelteKit - mentioning svelte-web3 there:

[Here is out post Building cryptocurrency site with Svelte, Python and TimescaleDB](https://tradingstrategy.ai/blog/building-cryptocurrency-website)
