### ISSUE TITLE
TypeScript types for release 3.*

### ISSUE THREAD

**Issue by clbrge** [clbrge/svelte-web3#23]
svelte-web3 is going to get a major upgrade 3.0 in a few days that would probably need a refresh of types declarations.
I'm not using typescript myself. Any volunteer to prepare the ts version ?
@Creskendoll do you want to follow up on your last PR ? 
pre release versions are in branch next/components & on npm.

**Comment by Creskendoll** [comment]
Hey, @clbrge yes I'd like to help out. I'll try to get it done asap but it might be late since it's the holiday season. You can release the new version if you want and we can add the types later.

**Comment by clbrge** [comment]
version 3 has been released...

**Comment by Creskendoll** [comment]
Types are updated. See https://github.com/clbrge/svelte-web3/pull/30
