### ISSUE TITLE
exports not defined

### ISSUE THREAD

**Issue by pythonicode** [clbrge/svelte-web3#26]
I'm getting the following error when importing from svelte-web3

> exports is not defined
> ReferenceError: exports is not defined

Here is more detailed logs
```
1:04:38 PM [vite] Error when evaluating SSR module /node_modules/svelte-proxied-store/dist/store.js?v=648dcf98:
ReferenceError: exports is not defined
    at eval (/node_modules/svelte-proxied-store/dist/store.js?v=648dcf98:5:23)
    at instantiateModule (C:\Users\antho\Desktop\Code\Tutorials\MyDapp\node_modules\vite\dist\node\chunks\dep-76613303.js:60094:15)
1:04:38 PM [vite] Error when evaluating SSR module /node_modules/svelte-web3/src/stores.js:
ReferenceError: exports is not defined
    at eval (/node_modules/svelte-proxied-store/dist/store.js?v=648dcf98:5:23)
    at instantiateModule (C:\Users\antho\Desktop\Code\Tutorials\MyDapp\node_modules\vite\dist\node\chunks\dep-76613303.js:60094:15)
1:04:38 PM [vite] Error when evaluating SSR module /src/routes/index.svelte:
ReferenceError: exports is not defined
    at eval (/node_modules/svelte-proxied-store/dist/store.js?v=648dcf98:5:23)
    at instantiateModule (C:\Users\antho\Desktop\Code\Tutorials\MyDapp\node_modules\vite\dist\node\chunks\dep-76613303.js:60094:15)
```

This is when importing from a newly instantiated SvelteKit project. Here is the code in my <script> tag:

```
        // IMPORT THESE
	import { browser } from '$app/env';
	import { defaultEvmStores, web3, selectedAccount, connected, chainId, chainData } from 'svelte-web3';

	// This will only render client-side if the browser is available.
	if(browser) {
		defaultEvmStores.setBrowserProvider();
	}
```

**Comment by clbrge** [comment]
Are you using TypeScript SvelteKit ? As far as i understand, it looks like a TypeScript error, right ?

**Comment by pythonicode** [comment]
> Are you using TypeScript SvelteKit ? As far as i understand, it looks like a TypeScript error, right ?

I'm not using Typescript, is it meant to work only in a Typescript project? I thought a JS project is compatible with TS packages. Or do I just need to install a typescript package before using svelte-web3?

**Comment by clbrge** [comment]
No it works with JavaScript and that's how i use it myself. Is there a way you could share your repo that shows that errors ?

**Comment by pythonicode** [comment]
> No it works with JavaScript and that's how i use it myself. Is there a way you could share your repo that shows that errors ?

I just published it here: https://github.com/PythoniCode/MyDapp

Thanks for looking into it so quickly.

**Comment by clbrge** [comment]
As a quick fix, you can just do `npm i svelte-proxied-store`
I'll post new version a bit later that will fix that problem without this workaround. 
Thanks for reporting the issue!

**Comment by clbrge** [comment]
Please upgrade to svelte-web3 version 3.0.2 . That should solve all Vite problems...
Thanks for taking the time to report the issue!
