### ISSUE TITLE
Easier way to async than via subscribe method

### ISSUE THREAD

**Issue by anthonychung14** [clbrge/svelte-web3#29]
Noticing that store values return an object with `subscribe` where we're expected to chain a callback.

Is there an `async` `await` means of being able to work with the values from web3? I'd like to do operations like determine how many items the user owns for a particular contract

**Comment by clbrge** [comment]
Could you give a example, and some speudo code of what you would expect. I'm not sure to understand.

**Comment by clbrge** [comment]
No feedback since January. Closing...
