### ISSUE TITLE
Deprecated event listener

### ISSUE THREAD

**Issue by antonio-fr** [clbrge/svelte-web3#36]
Running svelte-web3 with Metamask, the latter informs that the "close" may be removed in any future version.

_MetaMask: The event 'close' is deprecated and may be removed in the future. Please use 'disconnect' instead.
For more information, see: https://eips.ethereum.org/EIPS/eip-1193#disconnect_
```
 _warnOfDeprecation @ inpage.js:1
on @ inpage.js:1
u.setProvider @ web3.js:15
e @ web3.js:15
packageInit @ web3.js:3
d @ web3.js:15
set1193Provider @ stores.js:107
await in set1193Provider (async)  
setProvider @ stores.js:130
```

**Comment by clbrge** [comment]
I don't think the error surface from svelte-web3 itself. Which version are you using and which provider are you passing in setProvider ?

**Comment by antonio-fr** [comment]
Yes, after more analysis, this is the latest web.js module v1.7.0, which has this deprecated method. I'm closing this and will eventually open at the web3js repository.
