### ISSUE TITLE
Switching networks produce inconsistent network IDs

### ISSUE THREAD

**Issue by yaeszlo** [clbrge/svelte-web3#40]
Initially, connected wallet network ID will be represented as decimal integer, so for BSC that would be `56` and ETH `1`
But after wallet is opened and the network is switched, the `$chainId` produces `0x38` and `0x1` respectively.

**Comment by clbrge** [comment]
the selectedAccount store should be a string of the address connected & selected in the wallet, so I'm not sure how to understand the issue. Do you have a test case where the store produces a networkId (in whatever format)

**Comment by yaeszlo** [comment]
I am so sorry, obviously I was supposed to write `chainId`. Updating my issue

**Comment by clbrge** [comment]
Which provider did you connect to get this problem ?

**Comment by yaeszlo** [comment]
Browser provider `defaultEvmStores.setProvider()`

**Comment by clbrge** [comment]
Should be fixed in https://github.com/clbrge/svelte-web3/releases/tag/3.5.0
