### ISSUE TITLE
Is this library maintained?

### ISSUE THREAD

**Issue by Garito** [clbrge/svelte-web3#5]

**Comment by Garito** [comment]
Quite rude, thanks

**Comment by clbrge** [comment]
It was not really a question. But if you you have specific question, let me know.

**Comment by Garito** [comment]
That was totally a legit question since this library has no updates in the last 7 months and, of course, things have change (like the proper way to get the accounts)
Do you plan to update it?
Add more chains? Like binance

**Comment by kimxilxyong** [comment]
I'm rather interested, what's the proper way now to get the accounts? Tnx for info

**Comment by Garito** [comment]
https://docs.metamask.io/guide/getting-started.html#basic-considerations
Connecting to metamask (the link redirects to the parent basic considerations)

**Comment by clbrge** [comment]
> That was totally a legit question since this library has no updates in the last 7 months and, of course, things have change (like the proper way to get the accounts)
> Do you plan to update it?
> Add more chains? Like binance

Last version of web3 (1.3.0) cannot be bundled any more with rollup so this library may not be updated before web3 get clean up again. Not sure that it has any link with binance though.

**Comment by Garito** [comment]
Ok, thanks
What a shame you attitude cause the library is quite nice

**Comment by clbrge** [comment]
I was able to bundle the 1.2.9 version. Let me know if you have issues...

**Comment by Garito** [comment]
Sorry, I've already update my fork
