### ISSUE TITLE
SvelteKit and setProvider

### ISSUE THREAD

**Issue by oravecz** [clbrge/svelte-web3#9]
Shouldn't there be a way of enabling calls to `ethStore.setProvider(url)` when running in SSR mode?

I would like for my SvelteKit `load()` function to execute calls against my contract using the Infura interface. I have tried to initialize using the `browser` boolean for the conditional.

```js
ethStore.subscribe(async store => {
    if (browser) {
        await ethStore.setBrowserProvider();
    } else {
        await ethStore.setProvider(import.meta.env.VITE_INFURA_ADDRESS);
    }
});
```

Unfortunately, there doesn't seem to be any attempt to instantiate Web3 if it is not already loaded, which will only happen on the browser.

**Comment by clbrge** [comment]
Right. It's a good idea. I'll test that and clarify the docs.

**Comment by clbrge** [comment]
I have released a new version that should handle better this case. Could you try with version 2.0.0. Also could you use onMount for browser context and the load function inside <script module> for the ssr context.

**Comment by clbrge** [comment]
As far as I'm concerned, it works now since version 2.0.0.
